use_frameworks!

platform :ios, '9.0'

target 'DEF_Example' do
  #pod 'DEF', :path => '../'
   pod 'DEF', :podspec => '../DEF.podspec'

  target 'DEF_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
